version: '3.5'
services:
  mfcron:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      DB_HOST: set in docker-compose.override.yml
      DB_PORT: set in docker-compose.override.yml
      DB_USER: set in docker-compose.override.yml
      DB_DOMAIN: QUAL
      DB_PASS: set in docker-compose.override.yml
      DB_DATABASE: ITS-VCMS
    volumes:
      - ./src:/usr/app/src
